name: Deploy ASM to Staging

on:
  # Run this workflow on push to master (incl PR merges)
  push:
      branches: [ master ]

jobs:
  build:
    name: Build staging
    uses: zooniverse/ci-cd/.github/workflows/npm_build.yaml@main
    with:
      commit_id: ${{ github.sha }}
      node_version: '16.x'
      output: 'dist'
      script: 'build'
  deploy:
    name: Deploy staging
    uses: zooniverse/ci-cd/.github/workflows/deploy_static.yaml@main
    needs: build
    with:
      source: 'dist'
      target: 'preview.zooniverse.org/antislaverymanuscripts'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}
  slack_notification:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Build staging / build
      status: ${{ needs.deploy.result }}
      title: 'ASM Staging deploy complete'
      title_link: 'https://antislaverymanuscripts.preview.zooniverse.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
